import type { Metadata } from "next";
import { Instrument_Sans, Istok_Web, Jaldi } from "next/font/google";
import "./globals.css";
import Header from "@/component/header/Header";
import Footer from "@/component/footer/Footer";
import CustomCursor from "@/component/Cursor/CustomCursor";

// Define fonts with required weight property
const geistSans = Instrument_Sans({
  weight: ["400", "700"],      // add required weights
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Istok_Web({
  weight: ["400", "700"],      // add required weights
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const jaldiFont = Jaldi({
  weight: ["400", "700"],      // add required weights
  variable: "--font-jaldi",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Om Graphics",
  description: "Generated by create next app",
  icons :{
    icon: "/favicon.svg",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${jaldiFont.variable} antialiased`}
      >
        <CustomCursor />
      <Header />

        {children}
        <Footer />
      </body>
    </html>
  );
}